FROM eclipse-temurin:21-jre-jammy

ENV JAVA_TOOL_OPTIONS="--add-opens=java.base/java.nio=ALL-UNNAMED"
WORKDIR /app
COPY amps-connectors/build/libs/amps-connectors.jar /app/app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
